using System.Globalization;
using System.Net;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Nodes;
using SecondKey.Artifacts;
using SecondKey.Artifacts.Contracts;
using SecondKey.Artifacts.Verdicts;
using SecondKey.Evidence.Sarif;

namespace SecondKey.Evidence;

/// <summary>A file the report names with its digest.</summary>
public sealed record DigestedFile(string Name, string Sha256);

/// <summary>What the report is rendered from.</summary>
public sealed record ReportInput
{
    public required VerdictDocument Verdict { get; init; }

    public required ContractDocument Contract { get; init; }

    /// <summary>The gate's SARIF, summarized; null when the pack was assembled without it.</summary>
    public GateSummary? Gate { get; init; }

    /// <summary>The inputs of the verdict and of the pack, with their SHA-256.</summary>
    public required IReadOnlyList<DigestedFile> Digests { get; init; }

    public required DateTimeOffset GeneratedAt { get; init; }

    public required ToolInfo Tool { get; init; }
}

/// <summary>
/// The evidence report (C10, S14): one standalone HTML page an approver can read without
/// Second Key, a network or a script. Every value that came from a recording, a contract or
/// a SARIF log is HTML-encoded, and a content security policy forbids scripts and requests,
/// so recorded content can never act inside the report.
/// </summary>
public static class HtmlReport
{
    /// <summary>How many differences one exchange shows; verdict.json holds all of them.</summary>
    public const int DiffsShown = 50;

    private static readonly JsonSerializerOptions Readable = new() { Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping };

    public static string Render(ReportInput input)
    {
        ArgumentNullException.ThrowIfNull(input);
        var verdict = input.Verdict;
        var contract = input.Contract;
        var html = new StringBuilder();
        var title = contract.Metadata.Title ?? contract.Metadata.Name;

        html.Append("""
            <!doctype html>
            <html lang="en">
            <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'">
            <meta name="generator" content="secondkey">

            """);
        html.Append(Inv($"<title>Evidence — {E(title)} (revision {contract.Metadata.Revision})</title>\n"));
        html.Append("<style>").Append(Stylesheet).Append("</style>\n</head>\n<body>\n<main>\n");

        Masthead(html, input, title);
        Summary(html, verdict);
        Gate(html, input.Gate);
        Exchanges(html, verdict, contract, ExchangeClass.Regression, "regressions", "Regressions",
            "The candidate breaks a clause the legacy system keeps, gave no answer, or answers differently where neither a clause nor a normalization rule says the difference is acceptable. Each one blocks approval until the candidate is fixed or the contract is changed in a reviewed commit.");
        Exchanges(html, verdict, contract, ExchangeClass.FixCandidate, "fix-candidates", "Fix candidates",
            "The candidate keeps a clause the legacy system broke. The change may be exactly what was wanted, or a behaviour someone relies on; a person decides each one.");
        Clauses(html, verdict, contract);
        EqualUnderContract(html, verdict);
        Equal(html, verdict);
        Normalization(html, contract);
        Limitations(html, input);
        Integrity(html, input);

        html.Append(Inv($"""
            <footer>
            <p>Generated by {E(input.Tool.ToString())} at {E(Time(input.GeneratedAt))}. The verdict is computed by code alone: no language model takes part in it, and the same contract and run always give the same verdict.</p>
            </footer>
            </main>
            </body>
            </html>

            """));
        return html.ToString();
    }

    private static void Masthead(StringBuilder html, ReportInput input, string title)
    {
        var verdict = input.Verdict;
        var contract = input.Contract;
        var s = verdict.Summary;
        html.Append("<header>\n<p class=\"eyebrow\">Second Key · evidence pack</p>\n");
        html.Append(Inv($"<h1>{E(title)}</h1>\n"));
        var system = contract.Metadata.System is { } name ? $"System: {E(name)} · " : string.Empty;
        html.Append(Inv($"<p class=\"meta\">{system}contract <code>{E(contract.Metadata.Name)}</code> revision {contract.Metadata.Revision} · run <code>{E(verdict.Inputs.Run.RunId)}</code> · verdict made {E(Time(verdict.CreatedAt))}</p>\n"));

        html.Append("<div class=\"verdict\">\n");
        html.Append(Inv($"<span class=\"badge big {Css(verdict.Outcome)}\">Behaviour: {Word(verdict.Outcome).ToUpperInvariant()}</span>\n"));
        html.Append(input.Gate switch
        {
            null => "<span class=\"badge big muted\">Gate: not supplied</span>\n",
            { Passes: true } => "<span class=\"badge big pass\">Gate: PASS</span>\n",
            var gate => Inv($"<span class=\"badge big fail\">Gate: FAIL · {gate.Blocking.Count} blocking</span>\n"),
        });
        html.Append("</div>\n");

        var lead = verdict.Outcome switch
        {
            VerdictOutcome.Fail => Inv($"{s.Regression} of {s.Exchanges} compared exchange(s) {(s.Regression == 1 ? "is a regression" : "are regressions")}: the candidate must not be approved as it is."),
            VerdictOutcome.Review => Inv($"No regression. {s.FixCandidate} exchange(s) changed in a way the contract calls a fix; a person decides whether each change is wanted."),
            _ => Inv($"All {s.Exchanges} compared exchange(s) behave as the legacy system does, exactly or under the contract's rules."),
        };
        html.Append(Inv($"<p class=\"lead\">{E(lead)}</p>\n</header>\n"));
    }

    private static void Summary(StringBuilder html, VerdictDocument verdict)
    {
        var s = verdict.Summary;
        var c = s.Clauses;
        html.Append("<section id=\"summary\">\n<h2>Summary</h2>\n<div class=\"tiles\">\n");
        Tile(html, "Exchanges compared", s.Exchanges, s.Scenarios is { } scenarios ? Inv($"in {scenarios} scenario(s)") : null, null);
        Tile(html, "Equal", s.Equal, "identical", null);
        Tile(html, "Equal under contract", s.EqualUnderContract, "differences the contract explains", null);
        Tile(html, "Regressions", s.Regression, "block approval", s.Regression > 0 ? "fail" : null);
        Tile(html, "Fix candidates", s.FixCandidate, "a person decides", s.FixCandidate > 0 ? "review" : null);
        Tile(html, "Accepted clauses", c.Accepted, Inv($"{c.Exercised} exercised, {c.Unexercised} not"), c.Unexercised > 0 ? "review" : null);
        if (c.AbsenceShare is { } share)
        {
            html.Append(Inv($"<div class=\"tile\"><div class=\"n\">{share * 100:0}%</div><div class=\"label\">Absence share</div><div class=\"hint\">accepted clauses that say what must never happen</div></div>\n"));
        }

        html.Append("</div>\n</section>\n");
    }

    private static void Tile(StringBuilder html, string label, int value, string? hint, string? tone) =>
        html.Append(Inv($"<div class=\"tile{(tone is null ? string.Empty : " " + tone)}\"><div class=\"n\">{value}</div><div class=\"label\">{E(label)}</div>{(hint is null ? string.Empty : $"<div class=\"hint\">{E(hint)}</div>")}</div>\n"));

    private static void Gate(StringBuilder html, GateSummary? gate)
    {
        html.Append("<section id=\"gate\">\n<h2>Gate</h2>\n");
        if (gate is null)
        {
            html.Append("<p class=\"muted-text\">No gate results were supplied with this pack.</p>\n</section>\n");
            return;
        }

        var tools = string.Join(", ", gate.Logs.SelectMany(l => l.Runs.Select(r => r.Version is null ? r.Tool : $"{r.Tool} {r.Version}")).Distinct(StringComparer.Ordinal));
        html.Append(Inv($"<p>{gate.Logs.Count} SARIF log(s) from {E(tools)}: {gate.Findings} finding(s), <strong>{gate.Blocking.Count} blocking</strong>. An error blocks unless it is suppressed or already known from the baseline; warnings and notes are reported, not blocking.</p>\n"));
        html.Append("<table>\n<thead><tr><th>Rule</th><th>Tool</th><th class=\"num\">Errors</th><th class=\"num\">Warnings</th><th class=\"num\">Notes</th><th class=\"num\">Suppressed</th><th class=\"num\">Blocking</th></tr></thead>\n<tbody>\n");
        foreach (var rule in gate.Rules)
        {
            var description = rule.Description is null ? string.Empty : $"<div class=\"muted-text\">{E(rule.Description)}</div>";
            html.Append(Inv($"<tr><td><code>{E(rule.RuleId)}</code>{description}</td><td>{E(rule.Tool)}</td><td class=\"num\">{rule.Errors}</td><td class=\"num\">{rule.Warnings}</td><td class=\"num\">{rule.Notes}</td><td class=\"num\">{rule.Suppressed}</td><td class=\"num{(rule.Blocking > 0 ? " fail-text" : string.Empty)}\">{rule.Blocking}</td></tr>\n"));
        }

        html.Append("</tbody>\n</table>\n");
        if (gate.Blocking.Count > 0)
        {
            html.Append("<h3>Blocking findings</h3>\n<table>\n<thead><tr><th>Where</th><th>Rule</th><th>Message</th></tr></thead>\n<tbody>\n");
            foreach (var blocking in gate.Blocking)
            {
                html.Append(Inv($"<tr><td><code>{E(blocking.Finding.Location ?? "(no location)")}</code></td><td><code>{E(blocking.Finding.RuleId)}</code></td><td>{E(blocking.Finding.Message)}</td></tr>\n"));
            }

            html.Append("</tbody>\n</table>\n");
        }

        html.Append("</section>\n");
    }

    private static void Exchanges(StringBuilder html, VerdictDocument verdict, ContractDocument contract, ExchangeClass @class, string id, string heading, string explanation)
    {
        var exchanges = verdict.Exchanges.Where(e => e.Class == @class).ToList();
        html.Append(Inv($"<section id=\"{id}\">\n<h2>{E(heading)} <span class=\"count\">{exchanges.Count}</span></h2>\n<p class=\"muted-text\">{E(explanation)}</p>\n"));
        if (exchanges.Count == 0)
        {
            html.Append("<p>None.</p>\n</section>\n");
            return;
        }

        var titles = contract.Clauses.ToDictionary(c => c.Id, c => c.Title, StringComparer.Ordinal);
        foreach (var exchange in exchanges)
        {
            html.Append(Inv($"<article class=\"exchange\" id=\"{E(exchange.Exchange)}\">\n<div class=\"exchange-head\"><span class=\"badge {Css(exchange.Class)}\">{E(Word(exchange.Class))}</span> <code class=\"request\">{E(RequestLine(exchange.Request))}</code> <span class=\"muted-text\">{E(exchange.Exchange)} · scenario {E(exchange.Scenario)}</span></div>\n<ul class=\"reasons\">\n"));
            foreach (var reason in exchange.Reasons)
            {
                html.Append(Inv($"<li>{Reason(reason, titles)}</li>\n"));
            }

            html.Append("</ul>\n");
            Diffs(html, exchange.Diffs, exchange.Class);
            var broken = exchange.Clauses.Where(c => c.Legacy is ClauseOutcome.Fail or ClauseOutcome.Error || c.Candidate is ClauseOutcome.Fail or ClauseOutcome.Error).ToList();
            if (broken.Count > 0)
            {
                html.Append("<table class=\"compact\">\n<thead><tr><th>Clause</th><th>Legacy</th><th>Candidate</th><th>What was found</th></tr></thead>\n<tbody>\n");
                foreach (var clause in broken)
                {
                    html.Append(Inv($"<tr><td><code>{E(clause.Id)}</code></td><td>{Outcome(clause.Legacy)}</td><td>{Outcome(clause.Candidate)}</td><td>{E(clause.Detail ?? string.Empty)}</td></tr>\n"));
                }

                html.Append("</tbody>\n</table>\n");
            }

            html.Append("</article>\n");
        }

        html.Append("</section>\n");
    }

    private static void Diffs(StringBuilder html, IReadOnlyList<Difference> diffs, ExchangeClass @class)
    {
        // In a regression an unexplained difference is the problem; in a fix candidate it is the change a person decides on.
        var unexplained = @class == ExchangeClass.FixCandidate ? "<span class=\"muted-text\">—</span>" : "<span class=\"badge fail\">nothing</span>";
        if (diffs.Count == 0)
        {
            html.Append("<p class=\"muted-text\">The compared answers are identical; the class comes from the clauses alone.</p>\n");
            return;
        }

        html.Append("<table class=\"diffs\">\n<thead><tr><th>Path</th><th>Legacy</th><th>Candidate</th><th>Explained by</th></tr></thead>\n<tbody>\n");
        foreach (var diff in diffs.Take(DiffsShown))
        {
            var legacy = diff.Kind == DifferenceKind.Added ? "<span class=\"muted-text\">(absent)</span>" : $"<code>{E(Value(diff.Legacy))}</code>";
            var candidate = diff.Kind == DifferenceKind.Removed ? "<span class=\"muted-text\">(absent)</span>" : $"<code>{E(Value(diff.Candidate))}</code>";
            var rule = diff.NormalizedBy is { } by ? $"<span class=\"badge info\">{E(by)}</span>" : unexplained;
            html.Append(Inv($"<tr><td><code>{E(diff.Path)}</code></td><td>{legacy}</td><td>{candidate}</td><td>{rule}</td></tr>\n"));
        }

        html.Append("</tbody>\n</table>\n");
        if (diffs.Count > DiffsShown)
        {
            html.Append(Inv($"<p class=\"muted-text\">… and {diffs.Count - DiffsShown} more difference(s) in verdict.json.</p>\n"));
        }
    }

    private static void Clauses(StringBuilder html, VerdictDocument verdict, ContractDocument contract)
    {
        var definitions = contract.Clauses.ToDictionary(c => c.Id, StringComparer.Ordinal);
        html.Append(Inv($"<section id=\"clauses\">\n<h2>Clauses <span class=\"count\">{verdict.Clauses.Count}</span></h2>\n"));
        html.Append("<p class=\"muted-text\">What the contract says the system must do and must never do, and how each side did. Only accepted clauses decide; a proposed clause is evaluated and decides nothing until a person accepts it.</p>\n");
        html.Append("<table>\n<thead><tr><th>Clause</th><th>Status</th><th class=\"num\">Exercised</th><th>Legacy</th><th>Candidate</th></tr></thead>\n<tbody>\n");
        foreach (var clause in verdict.Clauses)
        {
            definitions.TryGetValue(clause.Id, out var definition);
            var why = definition is null ? string.Empty : $"<div class=\"muted-text\">Why: {E(definition.Why)}</div>";
            var proposed = clause.Accepted ? string.Empty : " <span class=\"badge muted\">proposed</span>";
            html.Append(Inv($"""
                <tr><td><code>{E(clause.Id)}</code> <span class="badge muted">{E(clause.Kind)}</span>{proposed}<div><strong>{E(clause.Title)}</strong></div><div>{E(clause.Text)}</div>{why}</td><td><span class="badge {Css(clause.Status)}">{E(Word(clause.Status))}</span></td><td class="num">{clause.Exercised}</td><td>{Tally(clause.Legacy)}</td><td>{Tally(clause.Candidate)}</td></tr>

                """));
        }

        html.Append("</tbody>\n</table>\n</section>\n");
    }

    private static void EqualUnderContract(StringBuilder html, VerdictDocument verdict)
    {
        var exchanges = verdict.Exchanges.Where(e => e.Class == ExchangeClass.EqualUnderContract).ToList();
        html.Append(Inv($"<section id=\"equal-under-contract\">\n<h2>Equal under contract <span class=\"count\">{exchanges.Count}</span></h2>\n"));
        html.Append("<p class=\"muted-text\">The answers differ only in ways the contract's normalization rules say do not matter. Each rule is part of the reviewed contract.</p>\n");
        if (exchanges.Count == 0)
        {
            html.Append("<p>None.</p>\n</section>\n");
            return;
        }

        html.Append("<table class=\"compact\">\n<thead><tr><th>Exchange</th><th>Request</th><th class=\"num\">Differences</th><th>Explained by</th></tr></thead>\n<tbody>\n");
        foreach (var exchange in exchanges)
        {
            var rules = string.Join(" ", exchange.Reasons.Select(r => $"<span class=\"badge info\">{E(r.StartsWith("normalized: ", StringComparison.Ordinal) ? r["normalized: ".Length..] : r)}</span>"));
            html.Append(Inv($"<tr><td>{E(exchange.Exchange)}</td><td><code>{E(RequestLine(exchange.Request))}</code></td><td class=\"num\">{exchange.Diffs.Count}</td><td>{rules}</td></tr>\n"));
        }

        html.Append("</tbody>\n</table>\n</section>\n");
    }

    private static void Equal(StringBuilder html, VerdictDocument verdict)
    {
        var exchanges = verdict.Exchanges.Where(e => e.Class == ExchangeClass.Equal).ToList();
        html.Append(Inv($"<section id=\"equal\">\n<h2>Equal <span class=\"count\">{exchanges.Count}</span></h2>\n"));
        if (exchanges.Count == 0)
        {
            html.Append("<p>None.</p>\n</section>\n");
            return;
        }

        html.Append("<table class=\"compact\">\n<thead><tr><th>Exchange</th><th>Scenario</th><th>Request</th></tr></thead>\n<tbody>\n");
        foreach (var exchange in exchanges)
        {
            html.Append(Inv($"<tr><td>{E(exchange.Exchange)}</td><td>{E(exchange.Scenario)}</td><td><code>{E(RequestLine(exchange.Request))}</code></td></tr>\n"));
        }

        html.Append("</tbody>\n</table>\n</section>\n");
    }

    private static void Normalization(StringBuilder html, ContractDocument contract)
    {
        var n = contract.Normalize;
        html.Append("<section id=\"normalization\">\n<h2>What the contract says does not matter</h2>\n<ul>\n");
        var headers = contract.Compare?.Headers ?? ["content-type", "location"];
        html.Append(Inv($"<li>Response headers compared: {string.Join(", ", headers.Select(h => $"<code>{E(h)}</code>"))}; every other header is not compared.</li>\n"));
        html.Append(contract.Compare?.Html == HtmlCompareMode.Text
            ? "<li>HTML pages are compared as text.</li>\n"
            : "<li>HTML pages are compared only through the values the contract extracts from them; markup is not compared.</li>\n");
        foreach (var path in n?.Ignore ?? [])
        {
            html.Append(Inv($"<li>Ignored: <code>{E(path)}</code></li>\n"));
        }

        foreach (var tolerance in n?.Tolerances ?? [])
        {
            var bound = tolerance.Absolute is { } a ? Inv($"±{a}") : Inv($"±{tolerance.Relative * 100}% of the larger value");
            // The bound is made of numbers formatted here, not recorded text, so it needs no encoding.
            html.Append(Inv($"<li>Tolerance: <code>{E(tolerance.Path)}</code> within {bound}</li>\n"));
        }

        foreach (var set in n?.Sets ?? [])
        {
            html.Append(Inv($"<li>Order does not matter: <code>{E(set.Path)}</code>{(set.Key is { } key ? $", elements matched by <code>{E(key)}</code>" : string.Empty)}</li>\n"));
        }

        if (n?.Masks?.Timestamps == true)
        {
            html.Append("<li>Masked: ISO-8601 date-times</li>\n");
        }

        if (n?.Masks?.Guids == true)
        {
            html.Append("<li>Masked: GUIDs</li>\n");
        }

        foreach (var pattern in n?.Masks?.Patterns ?? [])
        {
            html.Append(Inv($"<li>Masked: <code>{E(pattern.Name)}</code> — <code>{E(pattern.Regex)}</code></li>\n"));
        }

        html.Append("</ul>\n</section>\n");
    }

    private static void Limitations(StringBuilder html, ReportInput input)
    {
        var verdict = input.Verdict;
        var s = verdict.Summary;
        var items = new List<string>
        {
            Inv($"Only the recorded traffic was compared: {s.Exchanges} exchange(s){(s.Scenarios is { } n ? Inv($" in {n} scenario(s)") : string.Empty)}. Behaviour the recording did not exercise is not covered by this verdict."),
        };

        var unexercised = verdict.Clauses.Where(c => c.Accepted && c.Status == ClauseStatus.Unexercised).Select(c => c.Id).ToList();
        if (unexercised.Count > 0)
        {
            items.Add($"{unexercised.Count} accepted clause(s) were not exercised by any request and are not reported as passed: {string.Join(", ", unexercised)}.");
        }

        var proposed = verdict.Clauses.Count(c => !c.Accepted);
        if (proposed > 0)
        {
            items.Add(Inv($"{proposed} proposed clause(s) were evaluated and decided nothing."));
        }

        var violatedBoth = verdict.Clauses.Where(c => c.Accepted && c.Status == ClauseStatus.ViolatedBoth).Select(c => c.Id).ToList();
        if (violatedBoth.Count > 0)
        {
            items.Add($"{violatedBoth.Count} accepted clause(s) are broken on both sides — defects the migration preserved, which do not fail this verdict: {string.Join(", ", violatedBoth)}.");
        }

        if (input.Gate is null)
        {
            items.Add("No static analysis results (SARIF) were supplied, so this pack says nothing about the code itself.");
        }

        items.Add("This pack is not signed. statement.intoto.json names the SHA-256 of every file in it; signing that statement with the owner's key arrives in phase 03.");
        html.Append("<section id=\"limitations\">\n<h2>What this evidence does not show</h2>\n<ul>\n");
        foreach (var item in items)
        {
            html.Append(Inv($"<li>{E(item)}</li>\n"));
        }

        html.Append("</ul>\n</section>\n");
    }

    private static void Integrity(StringBuilder html, ReportInput input)
    {
        var verdict = input.Verdict;
        html.Append("<section id=\"integrity\">\n<h2>Integrity</h2>\n");
        html.Append("<p class=\"muted-text\">The verdict names the SHA-256 of the contract and the run it was computed from. Recomputing it — <code>sk compare --contract contract.yaml --run &lt;run&gt;</code> — gives the same verdict, apart from the time it was made.</p>\n");
        html.Append("<table class=\"compact\">\n<thead><tr><th>What</th><th>SHA-256</th></tr></thead>\n<tbody>\n");
        html.Append(Inv($"<tr><td>Contract <code>{E(verdict.Inputs.Contract.Path ?? verdict.Inputs.Contract.Name)}</code> (revision {verdict.Inputs.Contract.Revision})</td><td><code>{E(verdict.Inputs.Contract.Sha256)}</code></td></tr>\n"));
        html.Append(Inv($"<tr><td>Run <code>{E(verdict.Inputs.Run.Path ?? verdict.Inputs.Run.RunId)}</code></td><td><code>{E(verdict.Inputs.Run.Sha256)}</code></td></tr>\n"));
        foreach (var file in input.Digests)
        {
            html.Append(Inv($"<tr><td><code>{E(file.Name)}</code></td><td><code>{E(file.Sha256)}</code></td></tr>\n"));
        }

        html.Append("</tbody>\n</table>\n</section>\n");
    }

    private static string Reason(string reason, IReadOnlyDictionary<string, string> titles)
    {
        var colon = reason.IndexOf(':', StringComparison.Ordinal);
        var code = colon < 0 ? reason : reason[..colon];
        var argument = colon < 0 ? string.Empty : reason[(colon + 1)..].Trim();
        var title = titles.TryGetValue(argument, out var t) ? $" — {E(t)}" : string.Empty;
        return code switch
        {
            "missing-result" => $"<strong>No answer to compare</strong> from {E(argument)}.",
            "clause-regression" => $"<strong>Clause broken by the candidate</strong>, kept by legacy: <code>{E(argument)}</code>{title}.",
            "clause-fixed" => $"<strong>Clause kept by the candidate</strong>, broken by legacy: <code>{E(argument)}</code>{title}.",
            "uncovered-difference" => "<strong>Uncovered difference</strong>: the candidate answers differently, and neither a clause nor a normalization rule says the difference is acceptable.",
            _ => E(reason),
        };
    }

    private static string RequestLine(RequestLine request) => $"{request.Method} {request.Path}{request.Query}";

    private static string Value(JsonNode? node)
    {
        var text = node?.ToJsonString(Readable) ?? "null";
        return text.Length <= 300 ? text : text[..297] + "…";
    }

    private static string Outcome(ClauseOutcome outcome) => outcome switch
    {
        ClauseOutcome.Pass => "<span class=\"badge pass\">pass</span>",
        ClauseOutcome.Fail => "<span class=\"badge fail\">fail</span>",
        ClauseOutcome.Error => "<span class=\"badge fail\">error</span>",
        _ => "<span class=\"muted-text\">—</span>",
    };

    private static string Tally(Tally tally) =>
        Inv($"<span class=\"tally\">{tally.Pass} pass · {(tally.Fail > 0 ? $"<span class=\"fail-text\">{tally.Fail} fail</span>" : "0 fail")} · {(tally.Error > 0 ? $"<span class=\"fail-text\">{tally.Error} error</span>" : "0 error")}</span>");

    private static string Css(VerdictOutcome outcome) => outcome switch
    {
        VerdictOutcome.Fail => "fail",
        VerdictOutcome.Review => "review",
        _ => "pass",
    };

    private static string Css(ExchangeClass @class) => @class switch
    {
        ExchangeClass.Regression => "fail",
        ExchangeClass.FixCandidate => "review",
        ExchangeClass.EqualUnderContract => "info",
        _ => "pass",
    };

    private static string Css(ClauseStatus status) => status switch
    {
        ClauseStatus.Regressed => "fail",
        ClauseStatus.Fixed or ClauseStatus.Unexercised => "review",
        ClauseStatus.ViolatedBoth => "muted",
        _ => "pass",
    };

    private static string Word<T>(T value)
        where T : struct, Enum => JsonSerializer.Serialize(value).Trim('"');

    private static string Time(DateTimeOffset time) => time.ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss 'UTC'", CultureInfo.InvariantCulture);

    private static string E(string text) => WebUtility.HtmlEncode(text);

    private static string Inv(FormattableString text) => text.ToString(CultureInfo.InvariantCulture);

    private const string Stylesheet = """
        :root { --ink:#1b1f24; --muted:#5b6470; --line:#d9dee4; --panel:#f5f7f9;
          --fail:#b42318; --fail-bg:#fef3f2; --fail-line:#fecdca;
          --review:#a15c07; --review-bg:#fffaeb; --review-line:#fedf89;
          --pass:#067647; --pass-bg:#ecfdf3; --pass-line:#abefc6;
          --info:#175cd3; --info-bg:#eff8ff; --info-line:#b2ddff; }
        * { box-sizing: border-box; }
        html { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
        body { margin: 0; background: #fff; color: var(--ink); font: 14px/1.5 -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; }
        main { max-width: 1100px; margin: 0 auto; padding: 32px 24px 48px; }
        header { border-bottom: 3px solid var(--ink); padding-bottom: 16px; }
        h1 { font-size: 26px; line-height: 1.25; margin: 2px 0 6px; }
        h2 { font-size: 18px; margin: 34px 0 8px; padding-bottom: 6px; border-bottom: 1px solid var(--line); break-after: avoid; }
        h3 { font-size: 15px; margin: 18px 0 6px; }
        p { margin: 6px 0; }
        ul { margin: 6px 0; padding-left: 20px; }
        code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace; font-size: 12px; overflow-wrap: anywhere; }
        .eyebrow { margin: 0; text-transform: uppercase; letter-spacing: .08em; font-size: 11px; font-weight: 700; color: var(--muted); }
        .meta, .muted-text { color: var(--muted); }
        .lead { font-size: 15px; margin-top: 10px; }
        .verdict { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 14px; }
        .badge { display: inline-block; padding: 1px 8px; border: 1px solid var(--line); border-radius: 999px; font-size: 12px; font-weight: 600; white-space: nowrap; background: var(--panel); color: var(--muted); }
        .badge.big { font-size: 15px; padding: 6px 14px; border-radius: 8px; }
        .fail { color: var(--fail); background: var(--fail-bg); border-color: var(--fail-line); }
        .review { color: var(--review); background: var(--review-bg); border-color: var(--review-line); }
        .pass { color: var(--pass); background: var(--pass-bg); border-color: var(--pass-line); }
        .info { color: var(--info); background: var(--info-bg); border-color: var(--info-line); }
        .fail-text { color: var(--fail); font-weight: 600; }
        .count { display: inline-block; min-width: 24px; padding: 0 7px; border-radius: 999px; background: var(--panel); border: 1px solid var(--line); font-size: 13px; text-align: center; color: var(--muted); }
        .tiles { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 10px; }
        .tile { border: 1px solid var(--line); border-radius: 8px; padding: 10px 12px; background: #fff; }
        .tile .n { font-size: 26px; font-weight: 700; line-height: 1.2; }
        .tile .label { font-weight: 600; }
        .tile .hint { color: var(--muted); font-size: 12px; }
        .tile.fail .n, .tile.fail .label { color: var(--fail); }
        .tile.review .n, .tile.review .label { color: var(--review); }
        table { width: 100%; border-collapse: collapse; margin: 8px 0; font-size: 13px; }
        th, td { text-align: left; vertical-align: top; padding: 6px 8px; border-bottom: 1px solid var(--line); }
        th { background: var(--panel); font-weight: 600; }
        td.num, th.num { text-align: right; white-space: nowrap; }
        table.compact td, table.compact th { padding: 4px 8px; }
        tr { break-inside: avoid; }
        .exchange { border: 1px solid var(--line); border-left: 4px solid var(--line); border-radius: 8px; padding: 10px 14px; margin: 12px 0; }
        .exchange:has(.badge.fail) { border-left-color: var(--fail); }
        .exchange:has(.badge.review) { border-left-color: var(--review); }
        .exchange-head { display: flex; flex-wrap: wrap; align-items: baseline; gap: 8px; }
        .request { font-size: 13px; font-weight: 600; }
        .reasons { margin: 8px 0; }
        .tally { white-space: nowrap; }
        footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid var(--line); color: var(--muted); font-size: 12px; }
        @page { size: A4; margin: 14mm 12mm; }
        @media print { main { max-width: none; padding: 0; } h2 { margin-top: 24px; } .exchange { break-inside: avoid; } }
        """;
}
