using System.Text.Json.Nodes;
using SecondKey.Artifacts;
using SecondKey.Artifacts.Contracts;
using SecondKey.Artifacts.Verdicts;
using SecondKey.Evidence.Sarif;
using static SecondKey.Evidence.Tests.Fixtures;

namespace SecondKey.Evidence.Tests;

public class HtmlReportTests
{
    private static string Render(VerdictDocument? verdict = null, ContractDocument? contract = null, GateSummary? gate = null) => HtmlReport.Render(new ReportInput
    {
        Verdict = verdict ?? SampleVerdict(),
        Contract = contract ?? SampleContract().Document,
        Gate = gate,
        Digests = [new DigestedFile("verdict.json", new string('c', 64))],
        GeneratedAt = At,
        Tool = new ToolInfo("secondkey", "0.1.0", "abc1234"),
    });

    private static VerdictDocument WithExchanges(VerdictDocument verdict, Func<ExchangeVerdict, ExchangeVerdict> change) =>
        verdict with { Exchanges = verdict.Exchanges.Select(change).ToList() };

    [Fact]
    public void The_sample_report_says_what_was_decided_and_why()
    {
        var html = Render(gate: GateSummary.From([SarifLog.Read(SampleSarif)]));

        Assert.StartsWith("<!doctype html>", html, StringComparison.Ordinal);
        Assert.Contains("<title>Evidence — Sample shop — catalogue, cart and checkout (revision 1)</title>", html, StringComparison.Ordinal);
        Assert.Contains("Behaviour: FAIL", html, StringComparison.Ordinal);
        Assert.Contains("Gate: PASS", html, StringComparison.Ordinal);
        Assert.Contains("1 of 5 compared exchange(s) is a regression", html, StringComparison.Ordinal);
        Assert.Contains("<code class=\"request\">GET /products?sort=name</code>", html, StringComparison.Ordinal);
        Assert.Contains("<strong>Uncovered difference</strong>", html, StringComparison.Ordinal);
        Assert.Contains("<code>CHECKOUT-NEVER-5XX</code> — Checkout never answers with a server error.", html, StringComparison.Ordinal);
        Assert.Contains("Why: A 5xx at checkout loses the sale and says nothing the customer can act on.", html, StringComparison.Ordinal);
        Assert.Contains("<span class=\"badge info\">masks.guids</span>", html, StringComparison.Ordinal);
        Assert.Contains("PORTCULLIS_MIG_SYNC_OVER_ASYNC", html, StringComparison.Ordinal);
        Assert.Contains("Ignored: <code>response.body.json.generatedAt</code>", html, StringComparison.Ordinal);
        Assert.Contains("ORDER-HAS-LOCATION.", html, StringComparison.Ordinal);
        Assert.Contains("1 proposed clause(s) were evaluated and decided nothing.", html, StringComparison.Ordinal);
        Assert.Contains("<code>verdict.json</code></td><td><code>cccccccc", html, StringComparison.Ordinal);
        Assert.Contains("Generated by secondkey 0.1.0 (abc1234) at 2026-09-26 10:05:00 UTC", html, StringComparison.Ordinal);
        Assert.EndsWith("</html>\n", html, StringComparison.Ordinal);
    }

    [Fact]
    public void Nothing_can_run_or_load_inside_the_report()
    {
        var html = Render(gate: GateSummary.From([SarifLog.Read(SampleSarif)]));

        Assert.Contains("<meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'none'; style-src 'unsafe-inline'\">", html, StringComparison.Ordinal);
        Assert.DoesNotContain("<script", html, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("src=\"http", html, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("<link", html, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Recorded_content_is_encoded_wherever_it_appears()
    {
        const string Hostile = "<script>alert(1)</script>";
        var verdict = WithExchanges(SampleVerdict(), e => e.Exchange != "ex-000001" ? e : e with
        {
            Request = e.Request with { Path = "/<b>" },
            Scenario = "<i>",
            Diffs = [new Difference { Path = "response.body.json.<x>", Kind = DifferenceKind.Changed, Legacy = JsonValue.Create(Hostile), Candidate = JsonValue.Create("\"&") }],
        });
        var contract = SampleContract().Document with { Metadata = SampleContract().Document.Metadata with { Title = "<h1>Shop</h1>", System = "<sys>" } };
        var gate = GateSummary.From([SarifLog.Parse(
            """{ "version": "2.1.0", "runs": [ { "tool": { "driver": { "name": "<t>", "rules": [ { "id": "<R>", "shortDescription": { "text": "<desc>" } } ] } }, "results": [ { "ruleId": "<R>", "level": "error", "message": { "text": "<img src=x onerror=alert(1)>" }, "locations": [ { "physicalLocation": { "artifactLocation": { "uri": "%3Cp%3E.cs" } } } ] } ] } ] }""",
            "x.sarif")]);

        var html = Render(verdict, contract, gate);

        foreach (var raw in new[] { Hostile, "<b>", "<i>", "<x>", "<h1>Shop", "<sys>", "<t>", "<R>", "<desc>", "<img", "<p>.cs" })
        {
            Assert.DoesNotContain(raw, html, StringComparison.Ordinal);
        }

        Assert.Contains("&lt;script&gt;alert(1)&lt;/script&gt;", html, StringComparison.Ordinal);
        Assert.Contains("&lt;img src=x onerror=alert(1)&gt;", html, StringComparison.Ordinal);
        Assert.Contains("&quot;\\&quot;&amp;&quot;", html, StringComparison.Ordinal);
    }

    [Fact]
    public void Each_outcome_has_its_own_lead_and_badge()
    {
        var sample = SampleVerdict();
        var review = sample with
        {
            Outcome = VerdictOutcome.Review,
            Summary = sample.Summary with { Regression = 0 },
            Exchanges = sample.Exchanges.Where(e => e.Class != ExchangeClass.Regression).ToList(),
        };
        var pass = sample with
        {
            Outcome = VerdictOutcome.Pass,
            Summary = sample.Summary with { Regression = 0, FixCandidate = 0 },
            Exchanges = sample.Exchanges.Where(e => e.Class is ExchangeClass.Equal or ExchangeClass.EqualUnderContract).ToList(),
        };
        var twoRegressions = sample with { Summary = sample.Summary with { Regression = 2 } };

        Assert.Contains("Behaviour: REVIEW", Render(review), StringComparison.Ordinal);
        Assert.Contains("No regression. 1 exchange(s) changed in a way the contract calls a fix", Render(review), StringComparison.Ordinal);
        Assert.Contains("Behaviour: PASS", Render(pass), StringComparison.Ordinal);
        Assert.Contains("All 5 compared exchange(s) behave as the legacy system does", Render(pass), StringComparison.Ordinal);
        Assert.Contains("<h2>Regressions <span class=\"count\">0</span></h2>", Render(pass), StringComparison.Ordinal);
        Assert.Contains("2 of 5 compared exchange(s) are regressions", Render(twoRegressions), StringComparison.Ordinal);
    }

    [Fact]
    public void The_gate_badge_says_whether_a_gate_was_supplied_and_whether_it_blocks()
    {
        var blocking = GateSummary.From([SarifLog.Parse(
            """{ "version": "2.1.0", "runs": [ { "tool": { "driver": { "name": "Portcullis" } }, "results": [ { "ruleId": "PORTCULLIS_MIG_HTTPCONTEXT_CURRENT", "level": "error", "message": { "text": "HttpContext.Current" }, "locations": [ { "physicalLocation": { "artifactLocation": { "uri": "src/a.cs" }, "region": { "startLine": 4 } } } ] } ] } ] }""",
            "p.sarif")]);

        var none = Render();
        var failing = Render(gate: blocking);

        Assert.Contains("Gate: not supplied", none, StringComparison.Ordinal);
        Assert.Contains("No gate results were supplied with this pack.", none, StringComparison.Ordinal);
        Assert.Contains("No static analysis results (SARIF) were supplied", none, StringComparison.Ordinal);
        Assert.Contains("Gate: FAIL · 1 blocking", failing, StringComparison.Ordinal);
        Assert.Contains("<h3>Blocking findings</h3>", failing, StringComparison.Ordinal);
        Assert.Contains("<td><code>src/a.cs:4</code></td><td><code>PORTCULLIS_MIG_HTTPCONTEXT_CURRENT</code></td><td>HttpContext.Current</td>", failing, StringComparison.Ordinal);
        Assert.DoesNotContain("No static analysis results", failing, StringComparison.Ordinal);
    }

    [Fact]
    public void An_unexplained_difference_is_flagged_in_a_regression_and_neutral_in_a_fix_candidate()
    {
        var html = Render();
        var regression = html[html.IndexOf("id=\"regressions\"", StringComparison.Ordinal)..html.IndexOf("id=\"fix-candidates\"", StringComparison.Ordinal)];
        var fix = html[html.IndexOf("id=\"fix-candidates\"", StringComparison.Ordinal)..html.IndexOf("id=\"clauses\"", StringComparison.Ordinal)];

        Assert.Contains("<span class=\"badge fail\">nothing</span>", regression, StringComparison.Ordinal);
        Assert.DoesNotContain(">nothing<", fix, StringComparison.Ordinal);
        Assert.Contains("<td><span class=\"muted-text\">(absent)</span></td>", fix, StringComparison.Ordinal);
        Assert.Contains("<td><span class=\"badge fail\">fail</span></td><td><span class=\"badge pass\">pass</span></td><td>legacy: response.status = 500</td>", fix, StringComparison.Ordinal);
    }

    [Fact]
    public void Long_lists_of_differences_are_cut_and_long_values_shortened()
    {
        var many = Enumerable.Range(0, HtmlReport.DiffsShown + 7)
            .Select(i => new Difference { Path = $"response.body.json.items[{i}]", Kind = DifferenceKind.Changed, Legacy = JsonValue.Create(i), Candidate = JsonValue.Create(new string('x', 400)) })
            .ToList();
        var verdict = WithExchanges(SampleVerdict(), e => e.Exchange == "ex-000001" ? e with { Diffs = many } : e);

        var html = Render(verdict);

        Assert.Contains($"response.body.json.items[{HtmlReport.DiffsShown - 1}]", html, StringComparison.Ordinal);
        Assert.DoesNotContain($"response.body.json.items[{HtmlReport.DiffsShown}]", html, StringComparison.Ordinal);
        Assert.Contains("… and 7 more difference(s) in verdict.json.", html, StringComparison.Ordinal);
        Assert.Contains(new string('x', 296) + "…", html, StringComparison.Ordinal);
        Assert.DoesNotContain(new string('x', 298), html, StringComparison.Ordinal);
    }

    [Fact]
    public void An_exchange_decided_by_clauses_alone_says_its_answers_are_identical()
    {
        var verdict = WithExchanges(SampleVerdict(), e => e.Exchange == "ex-000005" ? e with { Diffs = [] } : e);

        Assert.Contains("The compared answers are identical; the class comes from the clauses alone.", Render(verdict), StringComparison.Ordinal);
    }

    [Fact]
    public void Clauses_show_their_status_tallies_and_whether_they_decide()
    {
        var html = Render();

        Assert.Contains("<code>PRODUCTS-PRICED</code> <span class=\"badge muted\">must</span> <span class=\"badge muted\">proposed</span>", html, StringComparison.Ordinal);
        Assert.Contains("<span class=\"badge review\">fixed</span>", html, StringComparison.Ordinal);
        Assert.Contains("<span class=\"badge muted\">violated-both</span>", html, StringComparison.Ordinal);
        Assert.Contains("1 pass · <span class=\"fail-text\">1 fail</span> · 0 error", html, StringComparison.Ordinal);
    }

    [Fact]
    public void Unexercised_accepted_clauses_are_named_as_a_limitation_and_regressed_ones_are_marked()
    {
        var sample = SampleVerdict();
        var verdict = sample with
        {
            Clauses = sample.Clauses.Select(c => c.Id switch
            {
                "CART-SHOWS-TOTAL-AND-LINES" => c with { Status = ClauseStatus.Unexercised, Exercised = 0 },
                "TOTAL-NEVER-NEGATIVE" => c with { Status = ClauseStatus.Regressed, Candidate = new Tally { Pass = 4, Fail = 0, Error = 1 } },
                _ => c,
            }).ToList(),
        };

        var html = Render(verdict);

        Assert.Contains("1 accepted clause(s) were not exercised by any request and are not reported as passed: CART-SHOWS-TOTAL-AND-LINES.", html, StringComparison.Ordinal);
        Assert.Contains("<span class=\"badge fail\">regressed</span>", html, StringComparison.Ordinal);
        Assert.Contains("<span class=\"badge review\">unexercised</span>", html, StringComparison.Ordinal);
        Assert.Contains("<span class=\"fail-text\">1 error</span>", html, StringComparison.Ordinal);
    }

    [Fact]
    public void A_run_with_nothing_to_show_says_none_rather_than_leaving_sections_out()
    {
        var sample = SampleVerdict();
        var empty = sample with
        {
            Exchanges = [],
            Clauses = sample.Clauses.Where(c => c.Accepted).Select(c => c with { Status = ClauseStatus.Held }).ToList(),
            Summary = sample.Summary with { Scenarios = null, Clauses = sample.Summary.Clauses with { AbsenceShare = null } },
        };

        var html = Render(empty);

        Assert.Equal(4, html.Split("<p>None.</p>").Length - 1);
        Assert.DoesNotContain("Absence share", html, StringComparison.Ordinal);
        Assert.DoesNotContain("proposed clause(s)", html, StringComparison.Ordinal);
        Assert.DoesNotContain("broken on both sides", html, StringComparison.Ordinal);
        Assert.Contains("Only the recorded traffic was compared: 5 exchange(s). Behaviour", html, StringComparison.Ordinal);
    }

    [Fact]
    public void Every_normalization_rule_and_compare_setting_is_listed()
    {
        var contract = SampleContract().Document with
        {
            Metadata = SampleContract().Document.Metadata with { System = null, Title = null },
            Compare = new CompareSettings { Headers = ["content-type", "x-total"], Html = HtmlCompareMode.Text },
            Normalize = new NormalizeSettings
            {
                Tolerances = [new ToleranceRule { Path = "response.body.json.rate", Relative = 0.02m }],
                Sets = [new SetRule { Path = "response.body.json.tags" }, new SetRule { Path = "response.body.json.items", Key = "sku" }],
                Masks = new MaskSettings { Patterns = [new MaskPattern { Name = "csrf", Regex = "value=\"[^\"]+\"", Replacement = "x" }] },
            },
        };

        var html = Render(contract: contract);

        Assert.Contains("<h1>sample-shop</h1>", html, StringComparison.Ordinal);
        Assert.DoesNotContain("System: ", html, StringComparison.Ordinal);
        Assert.Contains("Response headers compared: <code>content-type</code>, <code>x-total</code>;", html, StringComparison.Ordinal);
        Assert.Contains("HTML pages are compared as text.", html, StringComparison.Ordinal);
        Assert.Contains("Tolerance: <code>response.body.json.rate</code> within ±2.00% of the larger value", html, StringComparison.Ordinal);
        Assert.Contains("Order does not matter: <code>response.body.json.tags</code></li>", html, StringComparison.Ordinal);
        Assert.Contains("Order does not matter: <code>response.body.json.items</code>, elements matched by <code>sku</code>", html, StringComparison.Ordinal);
        Assert.Contains("Masked: <code>csrf</code> — <code>value=&quot;[^&quot;]+&quot;</code>", html, StringComparison.Ordinal);
        Assert.DoesNotContain("Masked: GUIDs", html, StringComparison.Ordinal);
        Assert.DoesNotContain("Masked: ISO-8601", html, StringComparison.Ordinal);
    }

    [Fact]
    public void A_contract_without_normalization_says_only_what_is_compared()
    {
        var contract = SampleContract().Document with { Compare = null, Normalize = null };

        var html = Render(contract: contract);

        Assert.Contains("Response headers compared: <code>content-type</code>, <code>location</code>;", html, StringComparison.Ordinal);
        Assert.Contains("HTML pages are compared only through the values the contract extracts from them", html, StringComparison.Ordinal);
        Assert.DoesNotContain("Ignored:", html, StringComparison.Ordinal);
    }

    [Fact]
    public void A_missing_answer_and_a_clause_regression_are_explained_in_words()
    {
        var verdict = WithExchanges(SampleVerdict(), e => e.Exchange == "ex-000001" ? e with { Reasons = ["missing-result: candidate (timeout)", "clause-regression: TOTAL-NEVER-NEGATIVE", "clause-regression: UNKNOWN-CLAUSE", "something-else"] } : e);

        var html = Render(verdict);

        Assert.Contains("<strong>No answer to compare</strong> from candidate (timeout).", html, StringComparison.Ordinal);
        Assert.Contains("<strong>Clause broken by the candidate</strong>, kept by legacy: <code>TOTAL-NEVER-NEGATIVE</code> — A cart or order total is never negative.", html, StringComparison.Ordinal);
        Assert.Contains("kept by legacy: <code>UNKNOWN-CLAUSE</code>.", html, StringComparison.Ordinal);
        Assert.Contains("<li>something-else</li>", html, StringComparison.Ordinal);
    }

    [Fact]
    public void Null_input_is_refused()
    {
        Assert.Throws<ArgumentNullException>(() => HtmlReport.Render(null!));
    }
}
